<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-FBV7UUO" failures="2" tests="8" name="Test" time="15.979" errors="0" timestamp="2024-06-07T00:48:00 IST">
  <testcase classname="CRUD_Operations.TestGET" name="pingRequest" time="2.537"/>
  <testcase classname="CRUD_Operations.TestGET" name="getReq" time="1.341">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at CRUD_Operations.TestGET.getReq(TestGET.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- getReq -->
  <testcase classname="CRUD_Operations.TestDELETE" name="pingRequest" time="1.27"/>
  <testcase classname="CRUD_Operations.TestDELETE" name="deleteReq" time="3.203"/>
  <testcase classname="CRUD_Operations.TestPOST" name="pingRequest" time="1.234"/>
  <testcase classname="CRUD_Operations.TestPOST" name="postReq" time="1.414"/>
  <testcase classname="CRUD_Operations.TestPUT" name="pingRequest" time="1.225"/>
  <testcase classname="CRUD_Operations.TestPUT" name="putReq" time="2.636">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at CRUD_Operations.TestPUT.putReq(TestPUT.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- putReq -->
  <testcase classname="baseClass.BasePage" name="@BeforeSuite init" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite init -->
  <testcase classname="baseClass.BasePage" name="@BeforeSuite init" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite init -->
  <testcase classname="baseClass.BasePage" name="@BeforeSuite init" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite init -->
</testsuite> <!-- Test -->
